In [1]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/MOp")

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/enrichment_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/gene_mapping_fxns.R")
source("/mnt/lareaulab/reliscu/code/upper_first.R")

library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [2]:
mod_def <- "PosBC"
unique <- FALSE

## Prep DE genes

### MOp DE genes

In [5]:
set_source <- "yao_2021_MOp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes"

pairwise_res_list <- readRDS("data/DE_genes/yao_2021_MOp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_dream.RDS")
marker_genes_list <- prep_DE_genes(pairwise_res_list, lfc_threshold, pairwise=TRUE, unique=unique)
names(marker_genes_list) <- unlist(sapply(names(marker_genes_list), function(x) gsub(" ", "_", x)))

In [6]:
marker_genes_list

$Astro
  [1] "Apoe"               "F3"                 "Gpr37l1"
  [4] "Cldn10"             "Slc1a3"             "Htra1"
  [7] "Pla2g7"             "Gjb6"               "Plpp3"
 [10] "Gja1"               "Ptprz1"             "S1pr1"
 [13] "Acsbg1"             "Slc39a12"           "S100a1"
 [16] "Lcat"               "Fam107a"            "S100a16"
 [19] "Tril"               "Cmtm5"              "Dio2"
 [22] "Slc25a18"           "Dbx2"               "Slc38a3"
 [25] "Kcnj10"             "Slco1c1"            "Cyp2j9"
 [28] "Ntsr2"              "Psd2"               "Mlc1"
 [31] "Cyp2d22"            "Fgfr3"              "Acss1"
 [34] "Atp1b2"             "Rftn2"              "Grin2c"
 [37] "Itih3"              "Ddah2"              "Fgf1"
 [40] "Nherf1"             "Mgst1"              "Gm6145"
 [43] "Ndrg2"              "Nwd1"               "Aqp4"
 [46] "St3gal4"            "Cyp4f15"            "Gpc5"
 [49] "Hepacam"            "Slc7a10"            "Aldoc"
 [52] "Slc15a2"            "Scrg1"              "Arhgef26"
 [55] "Gramd2b"            "Fabp7"              "Adgrg1"
 [58] "Gm5089"             "Gm3764"             "Chsy1"
 [61] "Fam20a"             "Fxyd3"              "Olig1"
 [64] "Plcd4"              "Btbd17"             "Aldh1l1"
 [67] "Mmd2"               "Car8"               "Cbs"
 [70] "Sox9"               "Mdk"                "Lgi4"
 [73] "Olfml1"             "AI849053"           "Vcam1"
 [76] "Mertk"              "Myo6"               "Pld2"
 [79] "Timp4"              "C030018K13Rik"      "Il18"
 [82] "Mks1"               "Tsc22d4"            "Bcan"
 [85] "Gm57100"            "Etnppl"             "Scd1"
 [88] "Tlr3"               "Gm10561"            "Gm26674"
 [91] "S100a13"            "Ccdc18"             "AW047730"
 [94] "Cpt1a"              "Aifm2"              "Gstm1"
 [97] "Qki"                "Col11a2"            "Ttpa"
[100] "Lppos"              "Fbxo30"             "Mir99ahg"
[103] "Abhd3"              "Gpt"                "Gm43823"
[106] "Plcb3"              "Ezr"                "Eva1a"
[109] "Chrdl1"             "Lfng"               "Cideb"
[112] "Mfsd2a"             "Nat1"               "Sema4b"
[115] "Mtss2"              "Scamp2"             "Ctso"
[118] "Gm26873"            "Nat8f5"             "Lgr6"
[121] "Gm56529"            "Slc26a6"            "2810403D21Rik"
[124] "Zfp521"             "Fads2"              "Apln"
[127] "Papss2"             "Eci1"               "Echdc3"
[130] "Cd38"               "Etv4"               "1700071M16Rik"
[133] "Steap3"             "Clmn"               "Tst"
[136] "0610005C13Rik"      "Glul"               "Kcnk10"
[139] "ENSMUSG00000121482" "Adora2b"            "Ednrb"
[142] "Fzd2"               "Nat8f3"             "Ston2"
[145] "Zfp142"             "Gm27151"            "Myo10"
[148] "Nim1k"              "Nat8f7"             "Naprt"
[151] "Pxmp2"              "Paqr6"              "Gm56816"
[154] "Vegfa"              "Nkain4"             "Gm45774"
[157] "Sash1"              "Gm36944"            "Fam181a"
[160] "Gm13322"            "Gstm2-ps1"          "Sycp2"
[163] "Gm16499-1"          "Nckap5"             "Asrgl1"
[166] "Tmem229a"           "2900052N01Rik"      "Rfx4"
[169] "Gm49708"            "Cst3"               "Gm20421"
[172] "Phkg1"              "Ccdc190"            "Gm29508"
[175] "Kirrel2"            "Mt2"                "Pou2f1"
[178] "Npc1"               "Amot"               "Gldc"
[181] "Ccdc50"             "Gli3"               "Gm44257"
[184] "Magef1"             "Frmd4a"             "Appl2"
[187] "Mcur1"              "Pnpla7"             "Cep85l"
[190] "Sfxn5"              "Mt1"                "Ivd"
[193] "Zhx3"               "Atp6v0e"            "Slc6a11"
[196] "Msi2"               "Gm13872"            "Washc2"
[199] "Lncpint"            "Mdga2"              "Gm12265"
[202] "Mpv17l2"            "Slc1a2"             "Gm26737"
[205] "Prdx6"              "Hacd2"              "Gm12224"
[208] "Rnft1"              "Tpp1"               "Acsl6"
[211] "Gm45875"            "Dbi"                "Macf1"
[214] "Snhg9"              "Dnaaf9"             "Cspg5"
[217] "Clu"                "Trappc6a"           "Rida"
[220] "Kcnk1"              "Rfc1"               "Ddhd1"
[223] "Gm44103"            "Hadhb"              "Gstm5"
[226] "Acsl3"              "Tm7sf2"             "Atl2"
[229] "Ap3m1"              "Acaa1a"             "Tprkb"
[232] "Spag9"              "Hmgn3"              "Asah1"
[235] "Ddx17"              "Msmo1"              "4933431E20Rik"
[238] "Pnisr"              "Ttyh1"              "Son"
[241] "Malat1"             "Mt3"

$Car3
 [1] "Rtn1"          "Gnb4"          "Nr4a2"         "Cpne4"
 [5] "1500009L16Rik" "Tbrg1"         "Oprk1"         "Ppp1r1a"
 [9] "Trem2"         "Ivns1abp"      "Gm34567"       "Col11a1"
[13] "Car3"          "Gm16277"       "Sh3d19"        "Gfra1"
[17] "Actr3b"        "Npbwr1"        "Gem"           "Tfap2d"
[21] "Pkp1"          "Itpkb"         "Gpd2"          "Atp2b2"
[25] "Lxn"

$L2_3_IT_CTX
 [1] "Olfm2"         "Itpka"         "Ptk2b"         "Shank1"
 [5] "Map9"          "Arhgef2"       "Vmp1"          "Tmem215"
 [9] "Il1rapl1"      "Rnd1"          "Myh7"          "Rfx3"
[13] "Tsnax"         "Ppp3ca"        "Sowaha"        "Tspoap1"
[17] "Btg3"          "F2rl2"         "Rilpl1"        "Megf9"
[21] "B230216N24Rik" "Fkbp1a"        "Aldh3b1"       "Gm42864"
[25] "Kcnh4"         "Hpgd"          "Tmem114"       "Gm10421"
[29] "Lrg1"          "Gm21814"       "Aldh3b2"       "Ppp1r36"
[33] "Stard8"        "Arr3"          "Kiss1r"        "Grin2b"
[37] "Gm56918"       "Hjv"           "Mhrt"          "Mdfic2"
[41] "Ccnjl"         "Ube2e3"        "Slc9a9"        "Lhfpl2"
[45] "Aldh1a3"       "Spata13"       "Gm47415"       "Pde7b"
[49] "Hcst"          "Tnfaip6"       "Ebf2"          "Gm10856"
[53] "Gm42865"       "Sub1"          "Spata21"       "Gm5546"
[57] "Mbnl2"         "Rnf125"        "Kntc1"         "Gm47328"
[61] "Ttc22"         "Tbx22"         "Tmem61"        "Fth1"
[65] "Sft2d1rt"

$L4_5_IT_CTX
 [1] "Nrsn1"         "Mef2c"         "Stx1a"         "Nudt4"
 [5] "Syt13"         "AI593442"      "Krt12"         "Tnnc1"
 [9] "A830036E02Rik" "Dnajc21"       "Stxbp1"        "Grm2"
[13] "Mb21d2"        "B4galt2"       "C030013G03Rik" "Adam33"
[17] "Hgf"           "Crhr1"         "Ptgfrn"        "Kcnh5"
[21] "Dapk2"         "Igtp"          "Gtdc1"         "Gm29674"
[25] "4921539H07Rik" "Zcchc2"        "Wnt9a"         "Lrrc4c"
[29] "Psg16"         "Sec16b"        "Adgrf4"        "Nhsl3"
[33] "C2cd4b"        "Lemd1"         "Ndfip1"        "2310040G24Rik"
[37] "Susd5"         "1700047F07Rik" "Xirp2"         "Cavin2"
[41] "Gm13601"       "Cyp39a1"       "Adra1d"        "Plb1"
[45] "Prox2os"       "Ocm"           "Gm7160"        "Mmel1"
[49] "Dnah5"         "Gm29506"       "Usp43"         "Ptprd"
[53] "Cd74"          "Dennd3"        "Gm20752"       "Fam237a"
[57] "Gm4204"        "Nap1l1"        "Nrxn1"

$L5_6_NP_CTX
 [1] "Lypd1"         "Dync1i1"       "Etv1"          "Gpr39"
 [5] "B3galnt1"      "Tshz2"         "Neto2"         "Camkv"
 [9] "Ldaf1"         "Plcxd2"        "Uap1"          "Stxbp2"
[13] "Myl4"          "Vwc2l"         "Efr3a"         "Amigo2"
[17] "Trhr"          "Chsy3"         "Grp"           "Slit1"
[21] "Abi3bp"        "Mirt1"         "Acvrl1"        "Myzap"
[25] "Pamr1"         "Ube3d"         "Ascl1"         "Cabcoco1"
[29] "Gm36543"       "Mndal"         "Lcp1"          "Kcna5"
[33] "Gm5454"        "Gm34294"       "Gm32679"       "Ccdc88b"
[37] "Mc3r"          "Pmfbp1"        "Avpr1a"        "Adrb2"
[41] "Il11ra1"       "Slc39a5"       "Mki67"         "Dcc"
[45] "4933429H19Rik" "Gm44643"       "Gm50394"       "Gm54215"
[49] "Mmp11"         "Gm49975"       "Gm57064"       "Ccl19-ps2"
[53] "4930560O18Rik" "Sla2"          "Gm4779"        "Gm19461"
[57] "Wscd1"         "Ccl19"         "Scarna2"       "Sec62"
[61] "Ssbp2"

$L5_IT_CTX
[1] "Napb" "Colq"

$L5_PT_CTX
 [1] "Ina"           "Igfbp4"        "Scn4b"         "Sgpp2"
 [5] "Layn"          "Polr2h"        "Npr3"          "Gm11730"
 [9] "Cox7a1"        "9930014A18Rik" "Gm14817"       "Nkiras1"
[13] "Sod2"

$L6_CT_CTX
 [1] "Ighm"          "Rprm"          "Ttc9b"         "Atp6v1g2"
 [5] "Klhdc3"        "Rprml"         "Trbc2"         "Adcy1"
 [9] "Garnl3"        "Lpgat1"        "Ramp3"         "Tmem178"
[13] "Ipcef1"        "Foxp2"         "Actl6b"        "Fancd2"
[17] "Tnfrsf21"      "Arhgap25"      "Pak5"          "Syt6"
[21] "Gm28221"       "Ubald1"        "Fam131b"       "Sebox"
[25] "Sla"           "Zfpm2"         "Sptbn5"        "Krt80"
[29] "Rasal1"        "Prss35"        "Obscn"         "Col5a1"
[33] "Gm10635"       "Med10"         "Gm35853"       "Urah"
[37] "Khdrbs3"       "Cpa6"          "Fxyd2"         "Aif1"
[41] "Zyx"           "Gm57143"       "Olfml2b"       "Aldh3a1"
[45] "Gm40518"       "Efhd2"         "Clcn1"         "Nrp1"
[49] "Ccdc12"        "Gm41673"       "Prss3l"        "Npdc1"
[53] "Gm45949"       "Cabp5"         "Gm29483"       "Ppp1r1b"
[57] "Tspan1"        "Gm57224"       "Alkal1"        "H60b"
[61] "Ceacam9"       "C330002G04Rik" "Ptges3l"       "Fancd2os"
[65] "Gm26974"       "Ly6d"          "Erfe"          "Fcmr"
[69] "Gm44284"       "Raet1d"        "Bsph1"         "Col23a1"
[73] "Gm39377"       "Ccm2l"         "Gm49525"       "Gm43066"
[77] "Gm28722"       "Gm11581"       "Il11ra3"       "1700003D09Rik"
[81] "Pgghg"         "Brd9"

$L6_IT_CTX
 [1] "Hpcal4"   "Blnk"     "Dmkn"     "Gm37811"  "Sh3bgrl3" "Zdhhc22"
 [7] "Adamts13" "Cd7"      "Slc26a4"  "Aspg"     "Plaur"    "Ntn5"
[13] "Gpc4"     "Htra4"    "Gm19744"  "Gpr52"    "Iqca1"    "Vegfd"
[19] "Ubxn11"   "Itga11"   "Gm6209"   "Gm11639"  "Gm32224"  "Nphs1"
[25] "Txk"

$L6b_CTX
 [1] "Serpini1"      "Cplx3"         "Ccn2"          "Bmerb1"
 [5] "Cnih2"         "Hpcal1"        "Fam163b"       "Gabra5"
 [9] "Fnbp1l"        "Kcnmb4"        "Ccdc25"        "N4bp2l1"
[13] "Nxph4"         "Tmod1"         "Srcin1"        "Nherf2"
[17] "Lpar1"         "Kcnmb4os2"     "Mapk8"         "Tnmd"
[21] "Tmem40"        "Pkp4"          "Clic5"         "Aldh1b1"
[25] "Ifitm7"        "Slf1"          "Stk26"         "Trh"
[29] "Tstd2"         "Kcnmb4os1"     "Ptger3"        "Bag1"
[33] "Gde1"          "Fzd10os"       "Fbxl7"         "Htr1d"
[37] "Grb7"          "Pth2r"         "Psd4"          "Lmbrd1"
[41] "Kcnip3"        "Prdx5"         "Gm48159"       "Serpinb11"
[45] "Cldnd1"        "Itga5"         "Smap1"         "Gm49266"
[49] "Scn10a"        "Fut9"          "Hbq1a"         "Usp46os2"
[53] "Atp6ap2"       "Or5v1"         "Cd164"         "C1qtnf1"
[57] "Pik3r5"        "4930538E20Rik" "Dynlrb1"       "Ube2b"
[61] "Rcn2"          "Phyhipl"       "Septin7"       "Eif4a2"
[65] "Gng12"         "Emc7"

$Lamp5
 [1] "Gad1"               "Rab3c"              "Gad2"
 [4] "Ogfrl1"             "Fgf13"              "Kit"
 [7] "Tceal8"             "Spock1"             "Crtac1"
[10] "Nsg2"               "Zmat4"              "Clstn3"
[13] "Pip4p1"             "Elovl4"             "Ndnf"
[16] "Rab6a"              "A830018L16Rik"      "Sv2c"
[19] "Nyap2"              "Tnnt1"              "Nmnat2"
[22] "Tceal5"             "Pde6d"              "Ankrd45"
[25] "Ngf"                "Rgs7bp"             "Ptprm"
[28] "Crispld1"           "Pde11a"             "Cryab"
[31] "Rpl21"              "Efcab6"             "Ddr2"
[34] "Chst7"              "Klhl33"             "Gdf10"
[37] "Slc35d3"            "Chd3"               "Grem2"
[40] "Gm16070"            "Arid5a"             "Fmo1"
[43] "Nfix"               "Baiap2l2"           "A230001M10Rik"
[46] "Gm3510"             "Gm44570"            "Kctd6"
[49] "Mia"                "Insyn1"             "Lefty2"
[52] "Vcan"               "Eif1b"              "Tsc22d1"
[55] "2610037D02Rik"      "Disp3"              "Myo3b"
[58] "2410004I01Rik"      "Gm6551"             "Fam83d"
[61] "Adprhl1"            "Arhgef37"           "Sp7"
[64] "Tgfbi"              "Ltbp2"              "Myo3a"
[67] "Odad1"              "ENSMUSG00000121399" "Hapln1"
[70] "Col4a4"             "Gm49942"            "Asph"
[73] "4833422M21Rik"      "Atp12a"             "Pdgfrl"
[76] "A2m"                "G430095P16Rik"      "Tex9"
[79] "Prom1"              "Slc6a1"             "Kidins220"
[82] "Tspan7"

$Pvalb
  [1] "Pvalb"         "Tac1"          "Cplx1"         "Asns"
  [5] "Sars1"         "Cox6a2"        "Kcnc2"         "Bend6"
  [9] "Ppp1cc"        "Gabrd"         "Sncb"          "Slc38a1"
 [13] "Glrx5"         "Hcn1"          "Kcnc1"         "Got2"
 [17] "Clec2l"        "Hspbp1"        "Rell2"         "Ndrg4"
 [21] "Vamp1"         "Pacsin2"       "Kcnab3"        "Kcnip2"
 [25] "Gm13629"       "Tm6sf1"        "Got1"          "Tafa2"
 [29] "Bzw2"          "Trnp1"         "Nt5m"          "Fgf12"
 [33] "St3gal6"       "Fchsd1"        "Ccdc184"       "Dnajc27"
 [37] "Lpl"           "Man1c1"        "Gpr176"        "Nxph2"
 [41] "Ndufs2"        "Esrrg"         "Inpp5j"        "Cacng2"
 [45] "Kcnk3"         "Th"            "Snhg4"         "Lrrc38"
 [49] "Cend1"         "Gars1"         "Nek7"          "Akr1c18"
 [53] "Syt2"          "Flt3"          "Fndc5"         "Adgra3"
 [57] "Gm10874"       "Ank1"          "Adamtsl5"      "Lsm4"
 [61] "Eya4"          "1700001O22Rik" "Mme"           "Cemip"
 [65] "Ostn"          "Dmac2"         "Stambpl1"      "Ppif"
 [69] "Nog"           "Nacc2"         "Btbd3"         "Bcl2l11"
 [73] "Kcnc3"         "Kctd17"        "Adamts8"       "Gm44832"
 [77] "4632428C04Rik" "Rnd2"          "Fez1"          "6330411D24Rik"
 [81] "Cerk"          "Lancl1"        "Zfp385a"       "Nme7"
 [85] "Ch25h"         "Mypn"          "Gm45760"       "Fgd3"
 [89] "Dcbld2"        "Clip4"         "Furin"         "Ndufa6"
 [93] "Scrt2"         "Macrod1"       "Auh"           "Gm37061"
 [97] "Atp1b1"        "Coprs"         "Gpnmb"         "Gm13554"
[101] "Sirt3"         "Gm14117"       "Btn2a2"        "Gm37711"
[105] "Cox7b"         "Hhatl"         "Aco2"          "C230035I16Rik"
[109] "Wnk4"          "Mdh1"          "Mrps11"        "Ddt"
[113] "Ndufb7"        "Fmc1"          "Ndufs7"        "Uqcc5"
[117] "Uqcrb"         "Tomm5"         "Cox6a1"        "Uqcrq"
[121] "Atp5f1b"       "Atp5pf"        "Ndufa12"       "Slc25a4"
[125] "Ndufa12-ps"    "Ndufs5"        "Atp5f1c"       "Ndufa8"
[129] "Ldhb-ps"       "Cyc1"          "Timm8a1"       "Ldhb"
[133] "Slc25a5"       "Chchd3"        "Atp5pd"        "Tsc22d3"
[137] "Gm10250"       "Ndufb11"       "Vegfb"

$`SMC-Peri`
  [1] "Vtn"                "Igfbp7"             "Myl9"
  [4] "Rgs5"               "Slc6a20a"           "Car4"
  [7] "Cald1"              "Higd1b"             "Nbl1"
 [10] "Acta2"              "Kcnj8"              "Esam"
 [13] "Tagln2"             "P2ry14"             "Gm13889"
 [16] "Hspb1"              "Arhgdib"            "Cfh"
 [19] "Perp"               "Gja4"               "Ndufa4l2"
 [22] "Slc38a11"           "Ifitm3"             "Art3"
 [25] "Coro1b"             "Cspg4"              "Ifitm1"
 [28] "Tagln"              "Ace2"               "Enpep"
 [31] "Ifitm2"             "S1pr3"              "4930523C07Rik"
 [34] "Rbpms"              "Crip1"              "Gper1"
 [37] "Atp13a5"            "Filip1l"            "BC028528"
 [40] "Gjc1"               "Gm9817"             "Slc1a5"
 [43] "Bgn"                "Colec12"            "Myo1b"
 [46] "Col4a1"             "Slc16a12"           "Ano1"
 [49] "Cox4i2"             "Ajuba"              "Kcnmb1"
 [52] "Pcolce"             "Atp2a3"             "Tm4sf1"
 [55] "Ankrd50"            "Slc12a2"            "Nodal"
 [58] "Ier2"               "Ppp1r14a"           "Gm13861"
 [61] "Tfpi"               "Eva1b"              "Carmn"
 [64] "Spry1"              "Hrct1"              "Itga1"
 [67] "Tbx2"               "Foxs1"              "Gm17120"
 [70] "Gm48529"            "Vstm4"              "Lama4"
 [73] "Foxf2"              "Cobll1"             "Gng11"
 [76] "Slc19a1"            "Ggt5"               "Tmod3"
 [79] "Trabd"              "Morrbid"            "Itga7"
 [82] "Mylip"              "Zic4"               "Cyba"
 [85] "Pth1r"              "Myl12a"             "Ogn"
 [88] "Mcam"               "Tcim"               "Eif4e3"
 [91] "Heyl"               "Foxc1"              "Rrad"
 [94] "Tbc1d1"             "S100a11"            "Pltp"
 [97] "Fcgrt"              "Abcc9"              "Vangl1"
[100] "Pld1"               "Spaar"              "Emcn"
[103] "Angptl2"            "Zic1"               "Myh11"
[106] "Pde3a"              "Casq2"              "Naalad2"
[109] "Ecm2"               "Utrn"               "Tinagl1"
[112] "Aspn"               "Lims1"              "Cd248"
[115] "Ets1"               "Plac9"              "Or51e1"
[118] "Rhoj"               "Ebf1"               "Gpx8"
[121] "Ahnak"              "Tmem134"            "Kcne4"
[124] "Serping1"           "Kirrel1"            "Dlc1"
[127] "Des"                "Tbx18"              "Fos"
[130] "Kank2"              "Pros1"              "Tbx3os1"
[133] "Gypc"               "Ddit4l"             "Pdgfrb"
[136] "Rcsd1"              "Gatm"               "Rhod"
[139] "Mxra8"              "Gstt2"              "Cnn2"
[142] "Tns2"               "Rbpms2"             "Sntb1"
[145] "Nid1"               "Emp3"               "Tmem109"
[148] "Notch3"             "Plekhg3"            "P3h2"
[151] "Eng"                "4930562F07Rik"      "Pde4c"
[154] "Cav1"               "Gm13536"            "Rcn3"
[157] "Cavin1"             "Tbx3"               "Hic1"
[160] "Sparc"              "Kdm1b"              "Dhx58os"
[163] "Adap2"              "Cped1"              "Hspb2"
[166] "Septin4"            "Gm13470"            "Prr5l"
[169] "Plscr2"             "Flvcr2"             "Gpr20"
[172] "Apcdd1"             "Ppic"               "ENSMUSG00000121791"
[175] "Foxd1"              "Lamc1"              "Rasl12"
[178] "Gm37477"            "Tuba1c"             "Trim56"
[181] "Amotl1"             "Lamc3"              "Tmem45a"
[184] "Kdelr3"             "Trim12a"            "Castor1"
[187] "Wfdc1"              "Tcf15"              "Ston1"
[190] "A4galt"             "Cmtm7"              "Smim5"
[193] "Sod3"               "Emilin1"            "Sdc2"
[196] "Rem1"               "Dennd6a"            "Tspo"
[199] "Anxa1"              "Lmod1"              "Lgals3"
[202] "Tcea3"              "Acadm"              "Gm57408"
[205] "Trim25"             "Irag1"              "Anxa3"
[208] "Gm26714"            "Anxa5"              "Dock6"
[211] "Tnfaip8"            "Gm10687"            "Ifnar2"
[214] "Smim11"             "Vim"                "Mprip"
[217] "Tmem51"             "Cd82"               "Txnip"
[220] "Hsp25-ps1"          "Anpep"              "Ccdc68"
[223] "Zfp36"              "Pear1"              "Hmgn1"
[226] "C920021L13Rik"      "Aoc3"               "Maml2"
[229] "Pakap-2"            "Itga10"             "Col1a2"
[232] "Gm49395"            "Gm57330"            "Junb"
[235] "Ephx1"              "Mrip-ps"            "Cd9"
[238] "Cdc42ep1"           "Vasp"               "Notch1"
[241] "Serinc3"            "Gm42922"            "Tcta"
[244] "Mettl25b"           "Zfhx3"              "Ech1"
[247] "Gm16243"            "2610027K06Rik"      "Gm14964"
[250] "Ptma"               "Tor1aip1"           "Rarres2"
[253] "Itm2b"              "Brd7"               "Laptm4a"
[256] "Dtx3"               "Cd81"

$Sncg
 [1] "Cnr1"               "Elmod1"             "Ccn3"
 [4] "Nrxn3"              "Kcnip1"             "Htr3a"
 [7] "Tnfaip8l3"          "Gsto1"              "Gng4"
[10] "Plppr1"             "Kctd12"             "Necab2"
[13] "Yjefn3"             "Egln3"              "Serpinf1"
[16] "Pbx3"               "Larp1b"             "Hspb6"
[19] "Sp8"                "Frem1"              "Crabp1"
[22] "Spock2"             "Enpp2"              "P2ry1"
[25] "Shisal2b"           "Spx"                "Intu"
[28] "Edn3"               "Krt73"              "Gm49227"
[31] "Ermn"               "Atp6v1g1"           "Insyn2b"
[34] "Calcb"              "Abat"               "ENSMUSG00000121783"
[37] "Gpx4"

$Sst_Chodl

### ACA DE genes

In [15]:
set_source <- "yao_2021_ACA_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes"

pairwise_res_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/ACA/data/DE_genes/yao_2021_ACA_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_dream.RDS")
marker_genes_list <- prep_DE_genes(pairwise_res_list, lfc_threshold, pairwise=TRUE, unique=unique)
names(marker_genes_list) <- unlist(sapply(names(marker_genes_list), function(x) gsub(" ", "_", x)))

# Convert to human markers
marker_genes_list <- lapply(marker_genes_list, convert_genes)

### Claude marker genes

In [3]:
set_source <- "Claude_marker_genes"

marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/AI/Claude_cortical_markers_mouse.RDS")

In [4]:
names(marker_genes_list) <- sapply(names(marker_genes_list), function(x) gsub(" ", "_", gsub("/", "_", x, fixed=TRUE)))

In [5]:
names(marker_genes_list)

 [1] "Astro"      "Chandelier" "Endo"       "L2_3_IT"    "L4_IT"
 [6] "L5_ET"      "L5_IT"      "L5_6_NP"    "L6_CT"      "L6_IT"
[11] "L6_IT_Car3" "L6b"        "Lamp5"      "Lamp5_Lhx6" "Micro_PVM"
[16] "OPC"        "Oligo"      "Pax6"       "Peri"       "Pvalb"
[21] "Sncg"       "Sst"        "Sst_Chodl"  "VLMC"       "Vip"

## Round 1 (cell_type, pcntVar = 20, mergeParam = 0.85)

In [ ]:
network_dir <- "yao_2021_MOp_STAR_20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.85_Modules"

In [ ]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [ ]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [ ]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  endothelial_cell
2  L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
3  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
4  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
5  oligodendrocyte
6  pvalb_GABAergic_cortical_interneuron
7  L6b_glutamatergic_cortical_neuron
8  VIP_GABAergic_cortical_interneuron
9  L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
10 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
11 sncg_GABAergic_cortical_interneuron
12 sst_chodl_GABAergic_cortical_interneuron
13 lamp5_GABAergic_cortical_interneuron
14 sst_GABAergic_cortical_interneuron
15 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
   Pval          Qval          Module
1  5.866048e-191 3.236299e-186 blue
2  9.766955e-136 2.694214e-131 turquoise
3  2.198092e-115 1.515859e-111 blue
4   1.783305e-68  1.130861e-65 darkgrey
5   6.124792e-66  3.754498e-63 yellow
6   2.787920e-55  1.201637e-52 green
7   1.143973e-47  4.322806e-45 grey60
8   3.647207e-42  1.183626e-39 orange
9   7.976835e-39  2.200410e-36 lightcyan
10  7.634755e-22  1.102643e-19 red
11  1.045791e-19  1.397005e-17 orange1
12  7.426164e-13  6.932343e-11 midnightblue
13  2.275318e-09  1.758114e-07 orchid
14  5.553511e-05  2.733160e-03 bisque3
15  1.325731e-04  6.074797e-03 turquoise
   Network
1  Bicor-None_signum0.342_minSize15_merge_ME_0.85_19017
2  Bicor-None_signum0.16_minSize15_merge_ME_0.85_19017
3  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
4  Bicor-None_signum0.342_minSize8_merge_ME_0.85_19017
5  Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017
6  Bicor-None_signum0.342_minSize15_merge_ME_0.85_19017
7  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
8  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
9  Bicor-None_signum0.0856_minSize15_merge_ME_0.85_19017
10 Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017
11 Bicor-None_signum0.207_minSize4_merge_ME_0.85_19017
12 Bicor-None_signum0.177_minSize15_merge_ME_0.85_19017
13 Bicor-None_signum0.0856_minSize6_merge_ME_0.85_19017
14 Bicor-None_signum0.0856_minSize8_merge_ME_0.85_19017
15 Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/yao_2021_MOp_pairwise_DE_genes_dream_unique", unique, "_", dataset, "_", mod_def, "_top_Qval_modules.csv"), row.names=FALSE, quote=FALSE)

## Round 2 (cell_type, SD = 25, mergeParam = 0.85)

In [7]:
network_dir <- "yao_2021_MOp_STAR_20pcntCells_25SD_200samples_pseudobulk_mergeParam0.85_Modules"
dataset <- "20pcntCells_25SD_200samples_pseudobulk_mergeParam0.85"

In [ ]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [ ]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [ ]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  pericyte
2  astrocyte
3  lamp5_GABAergic_cortical_interneuron
4  sst_chodl_GABAergic_cortical_interneuron
5  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
6  pvalb_GABAergic_cortical_interneuron
7  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
8  L6b_glutamatergic_cortical_neuron
9  VIP_GABAergic_cortical_interneuron
10 sncg_GABAergic_cortical_interneuron
11 L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
12 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
13 sst_GABAergic_cortical_interneuron
14 L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
15 corticothalamic-projecting_glutamatergic_cortical_neuron
16 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
   Pval          Qval          Module
1  4.313193e-320 2.904677e-315 blue
2  1.049342e-312 1.766673e-308 turquoise
3  2.746836e-152 2.936237e-149 magenta
4  6.746465e-145 6.584550e-142 magenta
5  2.129372e-131 1.815195e-128 black
6  1.022042e-130 8.603553e-128 black
7  8.882318e-116 5.864420e-113 darkgreen
8  6.924732e-109 3.985805e-106 greenyellow
9   4.683666e-99  2.205712e-96 tan
10  2.018060e-75  6.795213e-73 salmon
11  2.561485e-71  7.157702e-69 violet
12  4.484603e-65  1.052303e-62 lightgreen
13  7.197448e-49  1.400881e-46 darkturquoise
14  9.032231e-40  1.559658e-37 cyan
15  9.379915e-39  1.595154e-36 red
16  1.259983e-09  1.120902e-07 thistle1
   Network
1  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
2  Bicor-None_signum0.23_minSize6_merge_ME_0.85_20619
3  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
4  Bicor-None_signum0.668_minSize8_merge_ME_0.85_20619
5  Bicor-None_signum0.261_minSize12_merge_ME_0.85_20619
6  Bicor-None_signum0.668_minSize12_merge_ME_0.85_20619
7  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
8  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
9  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
10 Bicor-None_signum0.261_minSize15_merge_ME_0.85_20619
11 Bicor-None_signum0.261_minSize15_merge_ME_0.85_20619
12 Bicor-None_signum0.308_minSize12_merge_ME_0.85_20619
13 Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
14 Bicor-None_signum0.394_minSize6_merge_ME_0.85_20619
15 Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
16 Bicor-None_signum0.308_minSize6_merge_ME_0.85_20619

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_Qval_modules.csv"), row.names=FALSE, quote=FALSE)

## Round 3 (subclass_label, SD = 25, mergeParam = 0.95)

In [6]:
network_dir <- "yao_2021_MOp_STAR_SyntheticDataset1_subclass_label_20pcntCells_25SD_200samples_mergeParam0.95_subsetCutoff13.43_Modules"

In [7]:
names(marker_genes_list)

 [1] "Astro"      "Chandelier" "Endo"       "L2_3_IT"    "L4_IT"
 [6] "L5_ET"      "L5_IT"      "L5_6_NP"    "L6_CT"      "L6_IT"
[11] "L6_IT_Car3" "L6b"        "Lamp5"      "Lamp5_Lhx6" "Micro_PVM"
[16] "OPC"        "Oligo"      "Pax6"       "Peri"       "Pvalb"
[21] "Sncg"       "Sst"        "Sst_Chodl"  "VLMC"       "Vip"

In [8]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [9]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [10]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type  Pval         Qval         Module
1  Astro      2.317852e-25 1.528044e-20 turquoise
2  Peri       1.634223e-19 1.077361e-15 blue
3  Micro_PVM  9.436713e-18 4.443681e-14 springgreen
4  Vip        1.691505e-12 5.186627e-09 lightgreen
5  Pvalb      2.997053e-12 8.590467e-09 grey60
6  Sst_Chodl  3.614442e-12 1.013966e-08 pink
7  Sncg       1.417556e-09 3.398268e-06 skyblue
8  L2_3_IT    1.139346e-08 2.242131e-05 darkviolet
9  L6_IT_Car3 8.024143e-08 8.743663e-05 mediumorchid2
10 Endo       5.924912e-05 1.272312e-02 blue
11 Oligo      2.794272e-04 4.428183e-02 lightblue3
12 VLMC       1.207473e-03 1.317225e-01 turquoise
   Network
1  Bicor-None_signum0.582_minSize4_merge_ME_0.95_28835
2  Bicor-None_signum0.325_minSize6_merge_ME_0.95_28835
3  Bicor-None_signum0.582_minSize3_merge_ME_0.95_28835
4  Bicor-None_signum0.77_minSize6_merge_ME_0.95_28835
5  Bicor-None_signum0.582_minSize10_merge_ME_0.95_28835
6  Bicor-None_signum0.77_minSize10_merge_ME_0.95_28835
7  Bicor-None_signum0.77_minSize4_merge_ME_0.95_28835
8  Bicor-None_signum0.582_minSize6_merge_ME_0.95_28835
9  Bicor-None_signum0.582_minSize3_merge_ME_0.95_28835
10 Bicor-None_signum0.77_minSize3_merge_ME_0.95_28835
11 Bicor-None_signum0.77_minSize3_merge_ME_0.95_28835
12 Bicor-None_signum0.77_minSize6_merge_ME_0.95_28835

In [11]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)