In [1]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/MOp")

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/code/enrichment_fxns.R")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [2]:
mod_def <- "PosBC"
unique <- FALSE

## Prep DE genes

In [3]:
pairwise_res_list <- readRDS("data/DE_genes/yao_2021_MOp_STAR_donor_cell_type_pseudobulk_pairwise_DE_genes_dream.RDS")
pairwise_ctype_genes <- prep_DE_genes(pairwise_res_list, lfc_threshold, pairwise=TRUE, unique=unique)

## Round 1 (pcntVar = 20, mergeParam = 0.85)

In [ ]:
network_dir <- "yao_2021_MOp_STAR_20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.85_Modules"
dataset <- "20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.85"

In [12]:
pairwise_enrichments_df <- get_module_enrichments(network_dir, pairwise_ctype_genes, mod_def)

In [ ]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- pairwise_enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [ ]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  endothelial_cell
2  L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
3  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
4  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
5  oligodendrocyte
6  pvalb_GABAergic_cortical_interneuron
7  L6b_glutamatergic_cortical_neuron
8  VIP_GABAergic_cortical_interneuron
9  L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
10 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
11 sncg_GABAergic_cortical_interneuron
12 sst_chodl_GABAergic_cortical_interneuron
13 lamp5_GABAergic_cortical_interneuron
14 sst_GABAergic_cortical_interneuron
15 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
   Pval          Qval          Module
1  5.866048e-191 3.236299e-186 blue
2  9.766955e-136 2.694214e-131 turquoise
3  2.198092e-115 1.515859e-111 blue
4   1.783305e-68  1.130861e-65 darkgrey
5   6.124792e-66  3.754498e-63 yellow
6   2.787920e-55  1.201637e-52 green
7   1.143973e-47  4.322806e-45 grey60
8   3.647207e-42  1.183626e-39 orange
9   7.976835e-39  2.200410e-36 lightcyan
10  7.634755e-22  1.102643e-19 red
11  1.045791e-19  1.397005e-17 orange1
12  7.426164e-13  6.932343e-11 midnightblue
13  2.275318e-09  1.758114e-07 orchid
14  5.553511e-05  2.733160e-03 bisque3
15  1.325731e-04  6.074797e-03 turquoise
   Network
1  Bicor-None_signum0.342_minSize15_merge_ME_0.85_19017
2  Bicor-None_signum0.16_minSize15_merge_ME_0.85_19017
3  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
4  Bicor-None_signum0.342_minSize8_merge_ME_0.85_19017
5  Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017
6  Bicor-None_signum0.342_minSize15_merge_ME_0.85_19017
7  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
8  Bicor-None_signum0.207_minSize12_merge_ME_0.85_19017
9  Bicor-None_signum0.0856_minSize15_merge_ME_0.85_19017
10 Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017
11 Bicor-None_signum0.207_minSize4_merge_ME_0.85_19017
12 Bicor-None_signum0.177_minSize15_merge_ME_0.85_19017
13 Bicor-None_signum0.0856_minSize6_merge_ME_0.85_19017
14 Bicor-None_signum0.0856_minSize8_merge_ME_0.85_19017
15 Bicor-None_signum0.342_minSize12_merge_ME_0.85_19017

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/yao_2021_MOp_pairwise_DE_genes_dream_unique", unique, "_", dataset, "_", mod_def, "_top_Qval_modules.csv"), row.names=FALSE, quote=FALSE)

## Round 3 (SD = 25, mergeParam = 0.85)

In [4]:
network_dir <- "yao_2021_MOp_STAR_20pcntCells_25SD_200samples_pseudobulk_mergeParam0.85_Modules"
dataset <- "20pcntCells_25SD_200samples_pseudobulk_mergeParam0.85"

In [5]:
pairwise_enrichments_df <- get_module_enrichments(network_dir, pairwise_ctype_genes, mod_def)

In [ ]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- pairwise_enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [ ]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  pericyte
2  astrocyte
3  lamp5_GABAergic_cortical_interneuron
4  sst_chodl_GABAergic_cortical_interneuron
5  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
6  pvalb_GABAergic_cortical_interneuron
7  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
8  L6b_glutamatergic_cortical_neuron
9  VIP_GABAergic_cortical_interneuron
10 sncg_GABAergic_cortical_interneuron
11 L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
12 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
13 sst_GABAergic_cortical_interneuron
14 L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
15 corticothalamic-projecting_glutamatergic_cortical_neuron
16 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
   Pval          Qval          Module
1  4.313193e-320 2.904677e-315 blue
2  1.049342e-312 1.766673e-308 turquoise
3  2.746836e-152 2.936237e-149 magenta
4  6.746465e-145 6.584550e-142 magenta
5  2.129372e-131 1.815195e-128 black
6  1.022042e-130 8.603553e-128 black
7  8.882318e-116 5.864420e-113 darkgreen
8  6.924732e-109 3.985805e-106 greenyellow
9   4.683666e-99  2.205712e-96 tan
10  2.018060e-75  6.795213e-73 salmon
11  2.561485e-71  7.157702e-69 violet
12  4.484603e-65  1.052303e-62 lightgreen
13  7.197448e-49  1.400881e-46 darkturquoise
14  9.032231e-40  1.559658e-37 cyan
15  9.379915e-39  1.595154e-36 red
16  1.259983e-09  1.120902e-07 thistle1
   Network
1  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
2  Bicor-None_signum0.23_minSize6_merge_ME_0.85_20619
3  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
4  Bicor-None_signum0.668_minSize8_merge_ME_0.85_20619
5  Bicor-None_signum0.261_minSize12_merge_ME_0.85_20619
6  Bicor-None_signum0.668_minSize12_merge_ME_0.85_20619
7  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
8  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
9  Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
10 Bicor-None_signum0.261_minSize15_merge_ME_0.85_20619
11 Bicor-None_signum0.261_minSize15_merge_ME_0.85_20619
12 Bicor-None_signum0.308_minSize12_merge_ME_0.85_20619
13 Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
14 Bicor-None_signum0.394_minSize6_merge_ME_0.85_20619
15 Bicor-None_signum0.668_minSize6_merge_ME_0.85_20619
16 Bicor-None_signum0.308_minSize6_merge_ME_0.85_20619

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_Qval_modules.csv"), row.names=FALSE, quote=FALSE)