In [1]:
# conda activate anndata

import os
import sys

sys.path.append("/mnt/lareaulab/reliscu/code")

from junction2psi import *

In [ ]:
pseudobulk_data = "SyntheticDataset1_20pcntCells_25SD_200samples_SJ_pseudobulk"
sj_file = f"data/yao_2021_MOp_STAR_{pseudobulk_data}.csv"

In [3]:
# min_observed = 0.05
minPsi = 0.05

In [4]:
SJ_counts_table = pd.read_csv(sj_file, index_col=0)

In [5]:
SJ_counts_table.shape

(119662, 200)

In [6]:
SJ_counts_table = pd.read_csv(sj_file, index_col=0)

events_i1 = pd.Index([x[:-3] for x in SJ_counts_table.index if '_I1' in x])
events_i2 = pd.Index([x[:-3] for x in SJ_counts_table.index if '_I2' in x])
events_se = pd.Index([x[:-3] for x in SJ_counts_table.index if '_SE' in x])

events = events_i1.intersection(events_i2).intersection(events_se)
i1_events = [x + '_I1' for x in events]
I1_table = SJ_counts_table.loc[i1_events]
I1_table.index = events

i2_events = [x + '_I2' for x in events]
I2_table = SJ_counts_table.loc[i2_events]
I2_table.index = events

se_events = [x + '_SE' for x in events]
SE_table = SJ_counts_table.loc[se_events]
SE_table.index = events

In [7]:
len(events)

12022

In [8]:

I1_filt = I1_table.index[I1_table.sum(axis=1) > 0]
I2_filt = I2_table.index[I2_table.sum(axis=1) > 0]
SE_filt = SE_table.index[SE_table.sum(axis=1) > 0]
filtered_events = I1_filt.intersection(I2_filt).intersection(SE_filt)

I1_table = I1_table.loc[filtered_events]
I2_table = I2_table.loc[filtered_events]
SE_table = SE_table.loc[filtered_events]

psi = ((I1_table + I2_table) /(2*SE_table + I1_table + I2_table)).fillna(0)
reads = SE_table + I1_table + I2_table

In [9]:
I1_table

,Sample1,Sample2,Sample3,Sample4,Sample5,Sample6,Sample7,Sample8,Sample9,Sample10,...,Sample191,Sample192,Sample193,Sample194,Sample195,Sample196,Sample197,Sample198,Sample199,Sample200
ENSMUSG00000033845_ProteinCoding_1,12502,13383,10330,15205,13684,12444,10624,11337,11216,11449,...,11277,10942,13200,10747,12068,9538,13542,12376,11923,12431
ENSMUSG00000025903_ProteinCoding_1,2922,2892,2181,3023,2703,2707,2174,2152,2155,2352,...,2398,2164,2642,2287,2250,2144,2584,2408,2389,2446
ENSMUSG00000025903_ProteinCoding_2,3174,3131,2217,3271,2916,2833,2258,2353,2488,2581,...,2676,2296,2820,2452,2464,2179,2888,2838,2491,2636
ENSMUSG00000002459_ProteinCoding_1,1583,1887,1579,1867,1846,1719,1395,1501,1435,1670,...,1368,1307,1479,1581,1399,1272,1880,1366,1593,1382
ENSMUSG00000033793_ProteinCoding_1,17633,19436,14702,21076,19717,17965,15640,15431,16653,16554,...,16593,15597,18588,14826,17035,13952,19614,17510,16716,16740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000068457_ProteinCoding_1,87,142,50,123,85,97,95,117,68,105,...,123,105,113,122,86,107,116,118,117,71
ENSMUSG00000068457_ProteinCoding_2,288,323,251,453,314,366,294,331,256,283,...,370,257,262,328,266,232,384,382,316,239
ENSMUSG00000068457_NMD_3,7,1,0,4,0,0,0,0,0,0,...,3,3,0,0,0,0,0,0,1,0
ENSMUSG00000068457_NMD_4,0,0,3,2,3,1,0,1,0,0,...,0,0,1,0,0,4,0,0,0,0
ENSMUSG00000068457_NMD_5,7,5,0,7,12,0,0,0,0,5,...,10,0,0,0,5,5,0,0,0,5

In [10]:
I1_table.sum(axis=1)

ENSMUSG00000033845_ProteinCoding_1    2333160
ENSMUSG00000025903_ProteinCoding_1     469662
ENSMUSG00000025903_ProteinCoding_2     518105
ENSMUSG00000002459_ProteinCoding_1     307442
ENSMUSG00000033793_ProteinCoding_1    3319860
                                       ...
ENSMUSG00000068457_ProteinCoding_1      19467
ENSMUSG00000068457_ProteinCoding_2      57183
ENSMUSG00000068457_NMD_3                  145
ENSMUSG00000068457_NMD_4                  159
ENSMUSG00000068457_NMD_5                  509
Length: 12022, dtype: int64

In [11]:
len(filtered_events)

12022

In [12]:
psi.shape

(12022, 200)

In [13]:
# alt_exons = psi.index[np.abs(0.5-psi.mean(axis=1)) <= (0.5-minPsi)]
# obs_exons = psi.index[psi.mean(axis=1) <= 1-min_observed]
# # # selected_exons = alt_exons.intersection(obs_exons)
# selected_exons = obs_exons

In [14]:
psi.shape[0]

12022

In [16]:
reads.shape

(12022, 200)

In [17]:
reads

,Sample1,Sample2,Sample3,Sample4,Sample5,Sample6,Sample7,Sample8,Sample9,Sample10,...,Sample191,Sample192,Sample193,Sample194,Sample195,Sample196,Sample197,Sample198,Sample199,Sample200
ENSMUSG00000033845_ProteinCoding_1,20979,22245,17230,25461,22873,20857,17920,18833,18688,19363,...,18962,18421,22028,18162,20263,15995,22729,20892,19964,20736
ENSMUSG00000025903_ProteinCoding_1,6286,6235,4591,6419,5854,5575,4523,4535,4683,4981,...,5097,4597,5662,4913,4865,4533,5543,5205,4980,5173
ENSMUSG00000025903_ProteinCoding_2,5759,5612,4054,5813,5197,5046,4075,4253,4551,4528,...,4819,4227,5068,4392,4432,3998,5049,5016,4433,4672
ENSMUSG00000002459_ProteinCoding_1,2369,2838,2318,2849,2706,2566,2082,2213,2155,2465,...,1997,2001,2301,2325,2081,1888,2797,1994,2420,2072
ENSMUSG00000033793_ProteinCoding_1,37613,41737,31539,45430,41911,38617,33799,32897,35557,35443,...,35601,33377,39773,31851,36022,29562,42123,37148,35748,36095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000068457_ProteinCoding_1,273,389,179,486,303,359,287,328,262,321,...,419,302,338,389,322,286,358,393,357,245
ENSMUSG00000068457_ProteinCoding_2,658,696,502,929,658,799,642,674,513,616,...,780,553,562,654,618,477,758,735,633,518
ENSMUSG00000068457_NMD_3,374,412,284,436,313,443,336,343,263,293,...,387,258,258,308,320,243,342,352,358,297
ENSMUSG00000068457_NMD_4,363,372,265,474,358,434,348,344,257,333,...,407,293,301,326,352,260,374,353,316,279
ENSMUSG00000068457_NMD_5,377,417,284,441,330,443,336,343,263,300,...,400,254,257,308,326,250,342,353,357,304

In [15]:
# psi = psi.loc[selected_exons]
# reads = reads.loc[selected_exons]

In [ ]:
psi.to_csv(f"data/yao_2021_MOp_STAR_{pseudobulk_data}_PSI.csv")
reads.to_csv(f"data/yao_2021_MOp_STAR_{pseudobulk_data}_counts.csv")